version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hello_django_dev
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env.prod.pg-admin
    ports:
      - "5050:80"
    restart: always

volumes:
  postgres_data_dev:
