global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9913']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
