global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9913']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'pgadmin'
    static_configs:
      - targets: ['pgadmin:5050']

  - job_name: 'dozzle'
    static_configs:
      - targets: ['dozzle:8080']
