---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chiefbuilder-cm-app
  namespace: chiefbuilder
data:
  DJANGO_SETTINGS_MODULE: "hello_django.settings"
  SQL_ENGINE: "django.db.backends.postgresql"
  SQL_DATABASE: "hello_django_prod"
  SQL_USER: "db_user"
  SQL_HOST: "db"
  SQL_PORT: "5432"
  DJANGO_ALLOWED_HOSTS: "*"
  DEBUG: "False"
  DATABASE: "postgres"
  POSTGRES_DB: hello_django_prod
  PGADMIN_CONFIG_LOGIN_BANNER: "Authorisedusers"


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: chiefbuilder-cm-nginx-config
  namespace: chiefbuilder
data:
  nginx.conf: |
    # Your custom nginx configuration here
    upstream hello_django {
    server web:8000;
    }
    # Redirect log streams to stdout and stderr
    error_log /dev/stderr;
    access_log /dev/stdout;
    server {

        listen 80;

        location / {
            proxy_pass http://hello_django;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
      location /static/ {
            alias /home/app/web/staticfiles/;
        }
        location /metrics {
            # This assumes you have the exporter running on localhost:9913
            # Adjust accordingly based on your setup
            proxy_pass http://nginx-exporter:9913;
        }
    }