---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chiefbuilder-proxy-deployment
  namespace: chiefbuilder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: chiefbuilder/nginx-proxy
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-volume
          mountPath: /home/app/web/staticfiles
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: static-volume
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config

