apiVersion: v1
kind: Service
metadata:
  name: chiefbuilder-backend-service
  namespace: chiefbuilder
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIp