apiVersion: v1
kind: Service
metadata:
  name: chiefbuilder-nginx-service
  namespace: chiefbuilder
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort