name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on semantic version tags (e.g., v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Semantic Version
        id: version
        run: |
          # Extract version from Git tag (e.g., v1.0.0 → 1.0.0)
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Django Image
        uses: docker/build-push-action@v5
        with:
          context: ./django
          file: ./django/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/django-app:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest

      - name: Build and Push Nginx Image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-proxy:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-proxy:latest